"""Python implementation of the Guandan core model and rules.

The package mirrors the public behavior of the Dart ``guandan_core`` package
while exposing idiomatic Python dataclasses, enums, and snake_case helpers.
Wire strings and JSON keys remain Dart-compatible.
"""

from .cards import Card, Hand, HandType, PokerCardList, parse_hand_on_table
from .game_room import GameRoomConfig, PresetTimingMode, RoomMetadata, TimingConfig
from .game_state import (
    GameState,
    Phase,
    PlayerRank,
    Round,
    RoundResult,
    RoundSeries,
    TeamLevelRanks,
    TeamScores,
    Tribute,
    TributeResult,
    Turn,
)
from .hand_validator import detect_hand, validate_play, validate_return_card, validate_tribute_card
from .message import (
    AutoDelegationMessage,
    BotSelectionData,
    CardsOnHandMessage,
    CreateRoomRequest,
    ExtraTimeRequest,
    GameMessage,
    GameMessageFactory,
    GameRoomClosedMessage,
    GameRoomCreatedMessage,
    GameRoomMessage,
    HandPlayedMessage,
    HeartbeatMessage,
    JieFengMessage,
    JoinRoomRequest,
    JoinRoomResponsePayload,
    MessagePayload,
    MessageType,
    MoreTimeGrantedMessage,
    NewPhaseMessage,
    NewRoundMessage,
    NewRoundRequest,
    PayTributeResponsePayload,
    PayloadType,
    PlayHandResponsePayload,
    PlayerEmptiedHandMessage,
    PlayerJoinedRoomMessage,
    PlayerPayTributeRequest,
    PlayerPlayHandRequest,
    PlayerQuitRoomMessage,
    PlayerRemovedMessage,
    PlayerRequestMessage,
    PlayerReturnCardRequest,
    PlayerSeatMessage,
    PlayerTimeoutMessage,
    PreviousGameRoomPayload,
    QuitRoomRequest,
    RemovalReason,
    RequestResultMessage,
    ReturnCardMessage,
    ReturnCardResponsePayload,
    RoomOwnerMessage,
    RoundEndedMessage,
    RoundResultMessage,
    SeatRequest,
    ServerClosedMessage,
    ServerPlayHandRequest,
    ServerRequestMessage,
    ServerResponseCode,
    ServerReturnCardRequest,
    ServerTributeRequest,
    StartGameRequest,
    StartPlayerMessage,
    TeamScoresMessage,
    TributeCardMessage,
    TributeResistanceMessage,
    TributeResultMessage,
)
from .player import Player, PlayerPosition, PlayerTeam, get_player_position, next_player, next_seat

__all__ = [
    # Cards
    "Card",
    "Hand",
    "HandType",
    "PokerCardList",
    "parse_hand_on_table",
    # Game room
    "GameRoomConfig",
    "PresetTimingMode",
    "RoomMetadata",
    "TimingConfig",
    # Game state
    "GameState",
    "Phase",
    "PlayerRank",
    "Round",
    "RoundResult",
    "RoundSeries",
    "TeamLevelRanks",
    "TeamScores",
    "Tribute",
    "TributeResult",
    "Turn",
    # Hand validator
    "detect_hand",
    "validate_play",
    "validate_return_card",
    "validate_tribute_card",
    # Messages — enums
    "MessageType",
    "PayloadType",
    "RemovalReason",
    "ServerResponseCode",
    # Messages — base
    "GameMessage",
    "GameMessageFactory",
    "GameRoomMessage",
    "PlayerRequestMessage",
    "ServerRequestMessage",
    # Messages — payloads
    "BotSelectionData",
    "MessagePayload",
    "JoinRoomResponsePayload",
    "PayTributeResponsePayload",
    "PlayHandResponsePayload",
    "PreviousGameRoomPayload",
    "ReturnCardResponsePayload",
    # Messages — player requests
    "CreateRoomRequest",
    "ExtraTimeRequest",
    "JoinRoomRequest",
    "NewRoundRequest",
    "PlayerPayTributeRequest",
    "PlayerPlayHandRequest",
    "PlayerReturnCardRequest",
    "QuitRoomRequest",
    "SeatRequest",
    "StartGameRequest",
    # Messages — server requests
    "ServerPlayHandRequest",
    "ServerReturnCardRequest",
    "ServerTributeRequest",
    # Messages — informational broadcasts
    "AutoDelegationMessage",
    "CardsOnHandMessage",
    "GameRoomClosedMessage",
    "GameRoomCreatedMessage",
    "HandPlayedMessage",
    "HeartbeatMessage",
    "JieFengMessage",
    "MoreTimeGrantedMessage",
    "NewPhaseMessage",
    "NewRoundMessage",
    "PlayerEmptiedHandMessage",
    "PlayerJoinedRoomMessage",
    "PlayerQuitRoomMessage",
    "PlayerRemovedMessage",
    "PlayerSeatMessage",
    "PlayerTimeoutMessage",
    "RequestResultMessage",
    "ReturnCardMessage",
    "RoomOwnerMessage",
    "RoundEndedMessage",
    "RoundResultMessage",
    "ServerClosedMessage",
    "StartPlayerMessage",
    "TeamScoresMessage",
    "TributeCardMessage",
    "TributeResistanceMessage",
    "TributeResultMessage",
    # Player
    "Player",
    "PlayerPosition",
    "PlayerTeam",
    "get_player_position",
    "next_player",
    "next_seat",
]
