name: guandan_hand_splitter
description: Shared abstractions for splitting Guandan hands into multiple hands.
version: 1.0.195
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  guandan_core:
    path: ../guandan_core

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
